package MVCObserver.observer;

public enum NotificationStatus {
    PRESENTATION_ADDED,
    PRESENTATION_REMOVED,
    PRESENTATION_NAME_CHANGED,
    PROJECT_NAME_CHANGED,
    PROJECT_LOADED,
    PRESENTATION_AUTHOR_NAME_CHANGED,
    PRESENTATION_BACKGROUND_CHANGED,
    SLIDE_ADDED,
    SLIDE_REMOVED,
    SLOT_ADDED,
    SLOT_REMOVED,
    SLOT_MOVED,
    SLOT_SELECTED,
    SLOTS_DESELECTED,
    NOTHING
}
