package errors;

public enum ErrorTypes {
    EMPTY_AUTHOR_NAME,
    INVALID_PICTURE_EXTENSION,
    NO_PERMISSION_ERROR,
    NOTHING_SELECTED_ERROR,
    WRONG_COMPONENT_SELECTED,
    NO_OPENED_PRESENTATION,
    INTERSECTING_SLOTS
}
